<?php
// $Id$
/**
 * @file
 * OpenSourcery base feature and enhancements.
 */
include_once('os_base.features.inc');

/**
 * Implementation of hook_menu_alter().
 * Remove /node, as it might display the "Welcome to your new Drupal website!"
 * message, or a messy, unstyled node listing.
 */
function os_base_menu_alter(&$items) {
  unset($items['node']);
}

/**
 * Implementation of hook_block().
 */
function os_base_block($op = 'view', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $info = array(
        'account' => array('info' => t('OS Base: User account')),
      );
      return $info;
    case 'view':
      module_load_include('inc', 'os_base', 'os_base.block');
      $function = "_os_base_block_{$delta}";
      if (function_exists($function)) {
        drupal_add_js(drupal_get_path('module', 'os_base') .'/os_base.js');
        return call_user_func($function);
      }
      break;
  }

}

/**
 * Implementation of hook_form_alter().
 *
 * - Sets the revisions as enabled for new content types.
 */
function os_base_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'node_type_form':
      if (!isset($form['#node_type']->orig_type)) {
        $options = array();
        // Set to published by default.
        $options[] = 'status';
        // Enable revisions by default.
        $options[] = 'revision';
        $form['workflow']['node_options']['#default_value'] = $options;
      }
      break;
  }

  if (isset($form['type']['#value']) && $form_id == $form['type']['#value'] . '_node_form' && isset($form['revision_information'])) {
    // Hide the revision log input.
    $form['revision_information']['#access'] = FALSE;
  }
}

/**
 * Implementations of hook_date_format_types().
 */
function os_base_date_format_types() {
  return array(
    'day' => t('Day'),
    'time' => t('Time'),
  );
}

/**
 * Implementation of hook_date_formats().
 */
function os_base_date_formats() {
  $condensed = array(
    'day' => array(
      'j F Y',
      'l, M j',
      'l, j M',
      'n/j/Y',
    ),
    'time' => array(
      'g:ia',
      'H:i',
      'g:ia T',
    ),
  );
  $formats = array();
  foreach ($condensed as $type => $f) {
    foreach ($f as $format) {
      $formats[] = array(
        'type' => $type,
        'format' => $format,
        'locales' => array(),
      );
    }
  }
  return $formats;
}

/**
 * Preprocess page variables.
 */
function os_base_preprocess_page(&$vars) {
  if (isset($vars['footer_message'])) {
    // Replace @year with current year.
    $vars['footer_message'] = str_replace('@year', date('Y'), $vars['footer_message']);
  }
}

/**
 * Implementation of hook_theme_registry_alter().
 * Adds our preprocess function for regions right before zen_process().
 */
function os_base_theme_registry_alter(&$theme_registry) {
  global $theme_key;

  // We don't want to run for the admin theme
  $admin_theme = variable_get('admin_theme', $theme_key);
  if ($theme_key == $admin_theme || !isset($theme_registry['region'])) {
    return;
  }

  $preprocessors = array();
  foreach ($theme_registry['region']['preprocess functions'] as $function) {
    if ($function == 'zen_process') {
      $preprocessors[] = 'os_base_preprocess_region';
    }
    $preprocessors[] = $function;
  }
  $theme_registry['region']['preprocess functions'] = $preprocessors;
}

/**
 * Preprocess Zen regions: assign "dropdown-blocks" class to region(s).
 */
function os_base_preprocess_region(&$vars) {
  // determine which regions to use (but just once)
  static $dropdown_regions = NULL;
  if (!$dropdown_regions) {
    $dropdown_regions = array('header');
    drupal_alter('os_base_dropdown_regions_alter', $dropdown_regions);
  }

  if (in_array($vars['region'], $dropdown_regions)) {
    $vars['classes_array'][] = 'dropdown-blocks';
  }
}
