<?php
// $Id$
/**
 * @file
 * OpenSourcery base feature and enhancements.
 */
include_once('os_base.features.inc');

/**
 * Implementation of hook_block().
 */
function os_base_block($op = 'view', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $info = array(
        'account' => array('info' => t('OS Base: User account')),
      );
      return $info;
    case 'view':
      module_load_include('inc', 'os_base', 'os_base.block');
      $function = "_os_base_block_{$delta}";
      if (function_exists($function)) {
        return call_user_func($function);
      }
      break;
  }

}